name: Build and Upload

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/bun@v2
        with:
          bun-version: "1.1.25"
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run prod
